package com.example.myapplication.model.Enum;

public enum Categories {
    ELECTRONICS,
    FASHION,
    HOME_AND_GARDEN,
    BEAUTY_AND_HEALTH,
    SPORTS_AND_OUTDOORS,
    AUTOMOTIVE,
    TOYS_AND_CHILDREN,
    TRAVEL,
    BOOKS_AND_MAGAZINES,
    FOOD_AND_DRINK,
    COMPUTERS_AND_ACCESSORIES,
    PHONES_AND_ACCESSORIES,
    GAMING,
    PETS,
    SERVICES
}
